<?php
/**
 * FormTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Japan Impact Staffs
 *
 * This is the documentation for the front-office API of the new staffs infrastructure.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormTest Class Doc Comment
 *
 * @category    Class
 * @description Form
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Form"
     */
    public function testForm()
    {
    }

    /**
     * Test attribute "form_id"
     */
    public function testPropertyFormId()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "internal_name"
     */
    public function testPropertyInternalName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "max_age"
     */
    public function testPropertyMaxAge()
    {
    }

    /**
     * Test attribute "min_age"
     */
    public function testPropertyMinAge()
    {
    }

    /**
     * Test attribute "requires_staff"
     */
    public function testPropertyRequiresStaff()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {
    }
}
