<?php
/**
 * ApplicationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Japan Impact Staffs
 *
 * This is the documentation for the front-office API of the new staffs infrastructure.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ApplicationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getApplicationComments
     *
     * Returns all the public comments made on this application.
     *
     */
    public function testGetApplicationComments()
    {
    }

    /**
     * Test case for getApplicationReplies
     *
     * Returns the current content of an application.
     *
     */
    public function testGetApplicationReplies()
    {
    }

    /**
     * Test case for getApplicationState
     *
     * Returns the state of an application.
     *
     */
    public function testGetApplicationState()
    {
    }

    /**
     * Test case for updateApplicationReplies
     *
     * Sends some replies to add to the application..
     *
     */
    public function testUpdateApplicationReplies()
    {
    }

    /**
     * Test case for updateApplicationState
     *
     * Updates the state of an application.
     *
     */
    public function testUpdateApplicationState()
    {
    }
}
