<?php
/**
 * FormsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Japan Impact Staffs
 *
 * This is the documentation for the front-office API of the new staffs infrastructure.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FormsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FormsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCurrentForms
     *
     * Returns all the forms of the currently active events.
     *
     */
    public function testGetCurrentForms()
    {
    }

    /**
     * Test case for getCurrentMainForm
     *
     * Returns the main form of the current edition.
     *
     */
    public function testGetCurrentMainForm()
    {
    }

    /**
     * Test case for getFormById
     *
     * Returns the requested form, regardless of whether the edition is active or not.
     *
     */
    public function testGetFormById()
    {
    }

    /**
     * Test case for getFormPageByIdAndPosition
     *
     * Returns a specific page in the form.
     *
     */
    public function testGetFormPageByIdAndPosition()
    {
    }

    /**
     * Test case for getFormPagesById
     *
     * Returns the list of pages of a given form.
     *
     */
    public function testGetFormPagesById()
    {
    }
}
